services:
  notes:
    image: lordrahl/notes
    container_name: notes
    depends_on:
      - otel-lgtm
    build: .
    ports:
      - "8001:80"
    environment:
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4318
      OTEL_METRIC_EXPORT_INTERVAL: "5000"
    networks:
      - notes

  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel-lgtm
    ports:
      - "3010:3000"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
    volumes:
      - ./container/grafana:/data/grafana
      - ./container/prometheus:/data/prometheus
      - ./container/loki:/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    networks:
      - notes

networks:
  notes:
    driver: bridge