apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/lordrahl/notes:latest
          env:
            - name: TARGET
              value: "Go Sample v1"
