// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositories

import (
	"database/sql"
)

type Note struct {
	ID        int64
	NoteID    string
	Title     string
	Content   string
	UserID    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
