// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notes.sql

package repositories

import (
	"context"
)

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (note_id,title, content, user_id, created_at, updated_at)
VALUES (?,?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateNoteParams struct {
	NoteID  string
	Title   string
	Content string
	UserID  string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote,
		arg.NoteID,
		arg.Title,
		arg.Content,
		arg.UserID,
	)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
UPDATE notes
SET deleted_at = now()
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const findAllNotes = `-- name: FindAllNotes :many
SELECT id, note_id, title, content, user_id, created_at, updated_at, deleted_at
FROM notes
WHERE deleted_at IS NULL
`

func (q *Queries) FindAllNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, findAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNote = `-- name: FindNote :one
SELECT id, note_id, title, content, user_id, created_at, updated_at, deleted_at
FROM notes
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) FindNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, findNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findNoteByIDs = `-- name: FindNoteByIDs :many
SELECT id, note_id, title, content, user_id, created_at, updated_at, deleted_at
FROM notes
WHERE id IN (?)
  AND deleted_at IS NULL
`

func (q *Queries) FindNoteByIDs(ctx context.Context, id int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, findNoteByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNoteByTitle = `-- name: FindNoteByTitle :one
SELECT id, note_id, title, content, user_id, created_at, updated_at, deleted_at
FROM notes
WHERE title = ?
  AND deleted_at IS NULL
`

func (q *Queries) FindNoteByTitle(ctx context.Context, title string) (Note, error) {
	row := q.db.QueryRowContext(ctx, findNoteByTitle, title)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes
SET title      = ?,
    content    = ?,
    updated_at = now()
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateNoteParams struct {
	Title   string
	Content string
	ID      int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateNote, arg.Title, arg.Content, arg.ID)
	return err
}
